services:
    accounts:
        image: "aatmanpanseriya/accounts:s4"
        container_name: "accounts-ms"
        ports:
            - "8080:8080"
        deploy:
            resources:
                limits:
                    memory: 512m
        networks:
            - mb-common-network
    loans:
        image: "aatmanpanseriya/loans:s4"
        container_name: "loans-ms"
        ports:
            - "8090:8090"
        deploy:
            resources:
                limits:
                    memory: 512m
        networks:
            - mb-common-network
    cards:
        image: "aatmanpanseriya/cards:s4"
        container_name: "cards-ms"
        ports:
            - "9000:9000"
        deploy:
            resources:
                limits:
                    memory: 512m
        networks:
            - mb-common-network
networks:
    mb-common-network:
        driver: "bridge"