spring:
    application:
      name: "configserver"
    profiles:
      active: git
#        active: "native"
    cloud:
        config:
            server:
#              native:
#                search-locations: file:/home/aatman/Documents/config
#                search-locations: "classpath:/config"
               git:
                   uri: "https://github.com/aatman-24/ms-config.git"
                   default-label: main
                   timeout: 5
                   clone-on-start: true
                   force-pull: true
server:
    port: 8071